### ISSUE TITLE
SentinelAPIError: # HTTP Status 400 - Required String parameter 'q' is not present

### ISSUE THREAD

**Issue by adibratul** [derevirn/covid19-pollution#1]
Hello, 
I want to download sentine5p data using sentinelsat here is my following code  which shows error
```

from sentinelsat import SentinelAPI, geojson_to_wkt, read_geojson

user= 's5pguest'
password= 's5pguest'

area = r'map.geojson'



api= SentinelAPI(user, password,'http://s5phub.copernicus.eu/dhus')
footprint= geojson_to_wkt(read_geojson(area))

product_2020 = api.query(footprint, date=('20200101','20200101'),
                          producttype = 'L2__NO2___',)

#downloading 
api.download_all(product_2020, directory_path='/home/adib/COVID AIR/Mycode')

```
the error message is

```
runfile('/home/adib/COVID AIR/Mycode/Download Sentinel5p.py', wdir='/home/adib/COVID AIR/Mycode')
Traceback (most recent call last):

  File "/home/adib/COVID AIR/Mycode/Download Sentinel5p.py", line 23, in <module>
    producttype = 'L2__NO2___')

  File "/home/adib/anaconda3/lib/python3.7/site-packages/sentinelsat/sentinel.py", line 208, in query
    response, count = self._load_query(query, formatted_order_by, limit, offset)

  File "/home/adib/anaconda3/lib/python3.7/site-packages/sentinelsat/sentinel.py", line 349, in _load_query
    products, count = self._load_subquery(query, order_by, limit, offset)

  File "/home/adib/anaconda3/lib/python3.7/site-packages/sentinelsat/sentinel.py", line 387, in _load_subquery
    _check_scihub_response(response)

  File "/home/adib/anaconda3/lib/python3.7/site-packages/sentinelsat/sentinel.py", line 1320, in _check_scihub_response
    raise api_error

SentinelAPIError: # HTTP Status 400 - Required String parameter 'q' is not present

 **type** Status report

 **message** _Required String parameter 'q' is not present_

 **description** _The request sent by the client was syntactically incorrect._

* * *

### Apache Tomcat/8.0.36`
```

**Comment by derevirn** [comment]
Hello,

First of all, the end date data are not included in the query, so you should change that to '20200102'. Second, I suspect there's some kind of problem with map.geojson. In case you generated your own file, please upload it somewhere, so I can check it out.

**Comment by adibratul** [comment]
my geojson file 
https://drive.google.com/file/d/1qqGXQab4LUMpEXtbXGzEMpFLf78Frquz/view?usp=sharing

**Comment by derevirn** [comment]
There are no problems with the geojson file, but I detected some errors on your code. You should change the API connection URL to https://s5phub.copernicus.eu/dhus , and remove the comma after producttype = 'L2__NO2___' . It should work fine after fixing those typos.

**Comment by adibratul** [comment]
It works . Thanks

**Comment by adibratul** [comment]
> There are no problems with the geojson file, but I detected some errors on your code. You should change the API connection URL to https://s5phub.copernicus.eu/dhus , and remove the comma after producttype = 'L2__NO2___' . It should work fine after fixing those typos.

why all image is downloadedas Zip file but not in .nc file ?

**Comment by derevirn** [comment]
I believe it's a bug of the sentinelsat library. Only the filename extensions are wrong, and they are actually NetCDF files, so it's not a big problem.
